base_dir = pwd;

%% Add relevant toolboxes
addpath(base_dir)
addpath(genpath(fullfile('../helper_functions')))
% addpath(fullfile(base_dir,'GPT3.5vsGPT4/util'))

%% Constants
num_objects = 41;
num_pairs = nchoosek(num_objects, 2);

%% Load relevant data for humans
% Assuming human data has been processed into 41x41 matrices and saved similarly
data_dir = "data/consistency_plot/data/human_all_models_RSMs";
% Note: Ensure these files exist and contain 41x41 matrices.
% If you haven't generated human data for 41 objects, this part will error.
load(fullfile(data_dir,'RSM41_triplet.mat')); 
load(fullfile(data_dir,'RSM41_triplet_splithalf.mat'));

% Map loaded variables to generic names
% Adjust these variable names if your human data file uses different names
RDM_humans = RSM41_triplet;
RDM_split1_humans = RSM41_triplet_split1;
RDM_split2_humans = RSM41_triplet_split2;


%% Load relevant data for models
% Group models by input/model type so related bars stay adjacent.
model_names = { ...
    'qwen2_5_7B', 'gpt_oss', 'qwen3_235B', 'deepseek_r1','deepseek_v3_2','deepseek_v4','minimax_2_7',  ...
    'qwen2_5_7B_VL', 'qwen2_5_72B_VL', 'qwen3_5', ...
    'PE', 'VideoChat', 'HumanOmini', 'moments', 'VideoMAE', 'CoCa'};
XTick_names = { ...
    'Qwen2.5-7B', 'gpt-oss-120B', 'Qwen3-235B','Deepseek-R1-671B','Deepseek-V3.2-671B', 'Deepseek-V4-284B','MiniMax-V2.7',...
    'Qwen2.5-VL-7B', 'Qwen2.5-VL-72B',  'Qwen3.5-397B-A17B', ...
    'PerceptionEncoder', 'VideoChat', 'HumanOmni', 'Moments', 'VideoMAE', 'CoCa'};
model_groups = { ...
    'LLM', 'LLM', 'LLM', 'LLM', 'LLM','LLM', 'LLM',...
    'MLLM', 'MLLM', 'MLLM', ...
    'Feature', 'Feature', 'Feature', 'Feature', 'Feature', 'Feature'};

% Load the combined model data files generated by test4.py
models_data_file = fullfile(data_dir, 'RSM41_feature_models.mat');
models_split_data_file = fullfile(data_dir, 'RSM41_feature_models_splithalf.mat');

% Additional behavior model files
behavior_models_data_file = fullfile(data_dir, 'RSM41_behavior_models.mat');
behavior_models_split_data_file = fullfile(data_dir, 'RSM41_behavior_models_splithalf.mat');

fprintf('Loading model data...\n');
all_models_data = load(models_data_file);
all_models_split_data = load(models_split_data_file);

fprintf('Loading behavior model data...\n');
behavior_data = load(behavior_models_data_file);
behavior_split_data = load(behavior_models_split_data_file);

% Merge behavior data into main structures
fields = fieldnames(behavior_data);
for i = 1:numel(fields)
    all_models_data.(fields{i}) = behavior_data.(fields{i});
end

fields = fieldnames(behavior_split_data);
for i = 1:numel(fields)
    all_models_split_data.(fields{i}) = behavior_split_data.(fields{i});
end

% Initialize arrays to store results
rho_values = zeros(length(model_names), 1);
ci_lower = zeros(length(model_names), 1);
ci_upper = zeros(length(model_names), 1);

% Pre-calculate human vector
vec_humans = squareformq(RDM_humans);
vec_split1_humans = squareformq(RDM_split1_humans);
vec_split2_humans = squareformq(RDM_split2_humans);

% Bootstrap indices 
fprintf('Preparing bootstrap indices...\n');
rng(2)
try
    % Try to pre-allocate (faster)
    rnd = randi(num_pairs, num_pairs, 1000);
catch
    % Fallback if memory is insufficient
    warning('Not enough memory for full bootstrap matrix pre-allocation. Will generate indices in loop (slower).');
    rnd = [];
end

for model = 1:length(model_names)
    model_name = model_names{model};
    fprintf('Processing model: %s\n', model_name);
    
    % Check if model data exists
    if isfield(all_models_data, model_name)
        RDM_model = all_models_data.(model_name);
        
        % Check if split data exists
        split1_name = [model_name, '_split1'];
        split2_name = [model_name, '_split2'];
        
        if isfield(all_models_split_data, split1_name) && isfield(all_models_split_data, split2_name)
            RDM_split1_model = all_models_split_data.(split1_name);
            RDM_split2_model = all_models_split_data.(split2_name);
            
            % --- Data found: Perform calculations ---
            
            % 1. Compute human consistency (r_mh)
            vec_model = squareformq(RDM_model);
            r_mh = corr(vec_model, vec_humans);
            
            % 2. Bootstrap for CI
            r_boot = zeros(1, 1000);
            c1 = vec_model;
            c2 = vec_humans;
            
            if ~isempty(rnd)
                for i = 1:1000
                    r_boot(:,i) = corr(c1(rnd(:,i)), c2(rnd(:,i)));
                end
            else
                for i = 1:1000
                    curr_rnd = randi(num_pairs, num_pairs, 1);
                    r_boot(:,i) = corr(c1(curr_rnd), c2(curr_rnd));
                end
            end
            
            r_mh_ci95_lower = tanh(atanh(r_mh) - 1.96*std(atanh(r_boot),[],2));
            r_mh_ci95_upper = tanh(atanh(r_mh) + 1.96*std(atanh(r_boot),[],2));

            % 3. Compute noise ceiling correction
            vec_split1_model = squareformq(RDM_split1_model);
            vec_split2_model = squareformq(RDM_split2_model);
            
            r_mm = corr(vec_split1_model, vec_split2_model);
            r_hh = corr(vec_split1_humans, vec_split2_humans);

            numerator = r_mh;
            denominator = sqrt(r_mm * r_hh);
            rho = numerator / denominator;
            
            % Store calculated results
            rho_values(model) = rho;
            % Handle cases where rho is NaN (e.g. if model variance is 0)
            if isnan(rho), rho_values(model) = 0; end 
            
            ci_lower(model) = r_mh_ci95_lower + (rho-r_mh);
            ci_upper(model) = r_mh_ci95_upper + (rho-r_mh);
            
        else
            warning('Split data for model %s not found. Skipping.', model_name);
            % Values remain 0 (from initialization)
        end
    else
        warning('Model %s not found in data file. Setting as placeholder.', model_name);
        % Explicitly set to 0 or NaN to indicate placeholder
        rho_values(model) = 0; 
        ci_lower(model) = 0;
        ci_upper(model) = 0;
    end
    
    % add human-human consistency (calculate once)
    if model == 1
        % [保留您原代码中计算 Human-Human consistency 的部分]
        r_boot_hh = zeros(1, 1000);
        c1_hh = vec_split1_humans;
        c2_hh = vec_split2_humans;
        if ~isempty(rnd)
            for i = 1:1000
                r_boot_hh(:,i) = corr(c1_hh(rnd(:,i)), c2_hh(rnd(:,i)));
            end
        else
            for i = 1:1000
                curr_rnd = randi(num_pairs, num_pairs, 1);
                r_boot_hh(:,i) = corr(c1_hh(curr_rnd), c2_hh(curr_rnd));
            end
        end
        r_hh_ci95_lower = tanh(atanh(r_hh) - 1.96*std(atanh(r_boot_hh),[],2));
        r_hh_ci95_upper = tanh(atanh(r_hh) + 1.96*std(atanh(r_boot_hh),[],2));
    end
end

% Prepend Human data for plotting
rho_values = [r_hh; rho_values];
ci_lower = [r_hh_ci95_lower; ci_lower];
ci_upper = [r_hh_ci95_upper; ci_upper];
model_names_plot = [{'Human'}, model_names];
XTick_names = [{'Human'}, XTick_names];
model_groups_plot = [{'Human'}, model_groups];
fprintf('\n=== Final Consistency Values ===\n');
for k = 1:length(rho_values)
    fprintf('%-20s: %.4f\n', XTick_names{k}, rho_values(k));
end
fprintf('================================\n');

%% Plotting (publication style)
n_models_plot = length(model_names_plot);
x = 1:n_models_plot;
ci_low_err = rho_values - ci_lower;
ci_up_err = ci_upper - rho_values;

% Keep CI in visible range.
ci_low_err = max(ci_low_err, 0);
ci_up_err = max(ci_up_err, 0);

fig = figure('Units', 'centimeters', 'Position', [2 2 24 12], 'Color', 'w');
ax = axes('Parent', fig, 'Position', [0.08 0.24 0.88 0.70]);
hold(ax, 'on');

% Muted, journal-friendly palette by model group.
group_colors = struct();
group_colors.Human = [0.16 0.19 0.23];
group_colors.LLM = [0.28 0.45 0.64];
group_colors.MLLM = [0.22 0.57 0.54];
group_colors.Feature = [0.73 0.52 0.28];

bar_colors = zeros(n_models_plot, 3);
for i = 1:n_models_plot
    bar_colors(i, :) = group_colors.(model_groups_plot{i});
end

b = bar(ax, x, rho_values, 0.68, 'FaceColor', 'flat', 'EdgeColor', 'none');
b.CData = bar_colors;

eb = errorbar(ax, x, rho_values, ci_low_err, ci_up_err, ...
    'k', 'LineStyle', 'none', 'LineWidth', 1.2, 'CapSize', 7);
uistack(eb, 'top');

% Reference grid lines
y_grid = 0:0.2:1;
for yg = y_grid
    plot(ax, [0.5, n_models_plot + 0.5], [yg, yg], '-', ...
        'Color', [0.90 0.90 0.90], 'LineWidth', 0.8, 'HandleVisibility', 'off');
end
uistack(b, 'top');
uistack(eb, 'top');

% Axis settings
set(ax, 'XTick', x, ...
        'XTickLabel', XTick_names, ...
        'YTick', 0:0.1:1, ...
        'TickDir', 'out', ...
        'TickLength', [0.008 0.008], ...
        'LineWidth', 0.9, ...
        'Box', 'off', ...
        'FontName', 'Helvetica', ...
        'FontSize', 11, ...
        'XColor', [0.15 0.15 0.15], ...
        'YColor', [0.15 0.15 0.15]);
xtickangle(ax, 30);

xlim(ax, [0.5, n_models_plot + 0.5]);
ylim(ax, [0, 1.02]);

ylabel(ax, 'Noise-corrected human consistency (RSA)', ...
    'FontName', 'Helvetica', 'FontSize', 12, 'FontWeight', 'bold');
title(ax, 'Model-Human Behavioral Consistency', ...
    'FontName', 'Helvetica', 'FontSize', 13, 'FontWeight', 'bold');

% Compact numeric labels on top of bars.
for i = 1:n_models_plot
    y_text = min(1.01, rho_values(i) + ci_up_err(i) + 0.015);
    text(ax, x(i), y_text, sprintf('%.2f', rho_values(i)), ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'bottom', ...
        'FontName', 'Helvetica', ...
        'FontSize', 9, ...
        'Color', [0.20 0.20 0.20]);
end

% Export both vector and high-resolution raster.
exportgraphics(fig, 'human_behavioral_consistency_barplot.pdf', 'ContentType', 'vector');
close(fig);
